### ISSUE TITLE
I ran pulse leave not pulseha leave. it would be good not to see this.

### ISSUE THREAD

**Issue by akadata** [Syleron/pulseha#95]
Hi Andrew

I did a typo but the results do not look nice, especially the panic: messages

```bash
[root@pulse2 ~]# pulse leave

   ___       _                  _
  / _ \_   _| |___  ___  /\  /\/_\
 / /_)/ | | | / __|/ _ \/ /_/ //_\\
/ ___/| |_| | \__ \  __/ __  /  _  \  Version v0.0.1-192-g3c01b7f
\/     \__,_|_|___/\___\/ /_/\_/ \_/  Build   3c01b7f

[Dec  4 20:50:58][info] Loading configuration file
[Dec  4 20:50:58][WARNING] TLS Disabled! PulseHA server connection unsecured.
[Dec  4 20:50:58][error] Failed to listen: listen tcp 127.0.0.1:9443: bind: address already in use
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x9965d1]

goroutine 6 [running]:
google.golang.org/grpc.(*Server).Serve.func1(0xc420001c80, 0x0, 0x0)
	/root/go/src/google.golang.org/grpc/server.go:486 +0xb1
panic(0xa41a00, 0xf01b50)
	/usr/lib/golang/src/runtime/panic.go:491 +0x283
google.golang.org/grpc.(*Server).Serve(0xc420001c80, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/google.golang.org/grpc/server.go:495 +0x184
main.(*CLIServer).Setup(0xc420146090)
	/root/go/src/github.com/Syleron/PulseHA/src/cliserver.go:470 +0x183
created by main.main
	/root/go/src/github.com/Syleron/PulseHA/src/main.go:137 +0x1ab
[root@pulse2 ~]# pulseha leave
```

**Comment by matthewcooper** [comment]
This has been fix. Try running the main service whe the service is up report an error but no panic.
